--------------------------------------------------------
--  File created - Friday-December-23-2016   
--------------------------------------------------------
@D:\hprojects\PL-TSDB\METRIC_1.sql
@D:\hprojects\PL-TSDB\METRIC_ARR_1.sql
@D:\hprojects\PL-TSDB\METRIC_EXT_1.sql
@D:\hprojects\PL-TSDB\METRIC_EXT_ARR_1.sql
@D:\hprojects\PL-TSDB\TAGPAIR_1.sql
@D:\hprojects\PL-TSDB\TAGPAIR_ARR_1.sql
@D:\hprojects\PL-TSDB\VARCHAR2_ARR_1.sql
@D:\hprojects\PL-TSDB\TSDB_CONFIG_1.sql
@D:\hprojects\PL-TSDB\TSDB_METRIC_QUEUE_1.sql
@D:\hprojects\PL-TSDB\TSDB_METRIC_TAGSTORE_1.sql
@D:\hprojects\PL-TSDB\SYS_C0039588_1.sql
@D:\hprojects\PL-TSDB\SYS_C0039587_1.sql
@D:\hprojects\PL-TSDB\SYS_C0033870_1.sql
@D:\hprojects\PL-TSDB\SYS_FK0000118682N00004__1.sql
@D:\hprojects\PL-TSDB\TSDB_CONFIG_CONSTRAINT.sql
@D:\hprojects\PL-TSDB\TSDB_METRIC_QUEUE_CONSTRAINT.sql
@D:\hprojects\PL-TSDB\TSDB_TRACER_2.sql
@D:\hprojects\PL-TSDB\TSDB_UTIL_2.sql
@D:\hprojects\PL-TSDB\TSDB_TRACER_3.sql
@D:\hprojects\PL-TSDB\TSDB_UTIL_3.sql
