--------------------------------------------------------
--  DDL for Type METRIC_EXT
--------------------------------------------------------

  CREATE OR REPLACE TYPE "METRIC_EXT" FORCE AS OBJECT ( 
  METRIC_ID NUMBER,
  XROWID VARCHAR2(18),
  METRIC_STRING VARCHAR2(1800),
  CONSTRUCTOR FUNCTION METRIC_EXT(id IN NUMBER, xrow IN VARCHAR2, met IN METRIC) RETURN SELF AS RESULT
)
/
CREATE OR REPLACE TYPE BODY "METRIC_EXT" AS

  CONSTRUCTOR FUNCTION METRIC_EXT(id IN NUMBER, xrow IN VARCHAR2, met IN METRIC) RETURN SELF AS RESULT AS
  BEGIN
    SELF.METRIC_ID := id;
    SELF.XROWID := xrow;
    SELF.METRIC_STRING := met.JSONMS();
    RETURN;
  END METRIC_EXT;
END;

/
