-- Unable to render TABLE DDL for object PLTSDB.TSDB_METRIC_TAGSTORE with DBMS_METADATA attempting internal generator.
CREATE INDEX SYS_FK0000118682N00004$ ON TSDB_METRIC_TAGSTORE (NESTED_TABLE_ID ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE TSDB_METRIC_TAGSTORE 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
