--------------------------------------------------------
--  DDL for Table TSDB_METRIC_QUEUE
--------------------------------------------------------

  CREATE TABLE "TSDB_METRIC_QUEUE" 
   (	"METRIC_ID" NUMBER, 
	"M" "METRIC" 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "M"."TAGS" STORE AS "TSDB_METRIC_TAGSTORE"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;

   COMMENT ON COLUMN "TSDB_METRIC_QUEUE"."METRIC_ID" IS 'A queued metric id to sort by';
   COMMENT ON COLUMN "TSDB_METRIC_QUEUE"."M" IS 'A queued metric';
   COMMENT ON TABLE "TSDB_METRIC_QUEUE"  IS 'A table that serves as a queue when HTTP POST/TELNET options are not not available or not used';
