CREATE USER PLTSDB IDENTIFIED BY plt;
GRANT CREATE SESSION TO PLTSDB;
GRANT RESOURCE TO PLTSDB;
GRANT UNLIMITED TABLESPACE TO PLTSDB;
GRANT EXECUTE ON DBMS_LOCK TO PLTSDB;
GRANT EXECUTE ON DBMS_TRANSACTION to PLTSDB;
GRANT EXECUTE ON DBMS_ALERT TO PLTSDB;
GRANT EXECUTE ON DBMS_APPLICATION_INFO TO PLTSDB;
GRANT EXECUTE ON DBMS_SQL TO PLTSDB;
GRANT EXECUTE ON DBMS_SESSION TO PLTSDB;
GRANT SELECT ON V_$TRANSACTION TO PLTSDB;
GRANT SELECT ON v_$MYSTAT to PLTSDB;
GRANT SELECT ON v_$OSSTAT to PLTSDB;
GRANT SELECT ON v_$STATNAME to PLTSDB;
GRANT SELECT ON V_$EVENT_NAME to PLTSDB;
GRANT SELECT ON V_$WAITCLASSMETRIC to PLTSDB;

BEGIN
  DBMS_NETWORK_ACL_ADMIN.CREATE_ACL(acl=>'pltsdb.xml', description=>'PL/TSDB Network Access Control', principal=>'PLTSDB', is_grant=>TRUE, privilege=>'connect');
  COMMIT;
END;

/

BEGIN 
  DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(acl=>'pltsdb.xml',host=>'*'); 
  COMMIT;
END;

/
